name: dubmeio
description: Dubme.io interview task
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  cupertino_icons: ^1.0.8
  dubmeio_utils:
    path: packages/dubmeio_utils
  dubmeio_widgets:
    path: packages/dubmeio_widgets
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_gen: ^5.4.0
  flutter_localizations:
    sdk: flutter
  go_router: ^14.0.2
  intl: ^0.19.0
  provider: ^6.1.2
  sliver_tools: ^0.2.12
  uuid: ^4.4.0

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
