name: dubmeio
description: Dubme.io interview task
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  dubmeio_utils:
    path: packages/dubmeio_utils
  dubmeio_widgets:
    path: packages/dubmeio_widgets
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_gen: ^5.4.0
  flutter_localizations:
    sdk: flutter
  go_router: ^14.0.2
  intl: ^0.18.1
  provider: ^6.1.2

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
