name: dubmeio_widgets
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  dubmeio_utils:
    path: ../dubmeio_utils
  flutter:
    sdk: flutter
  go_router: ^14.0.2
  sliver_tools: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
